[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "edu-portal"
version = "0.1.0"
description = "Edu-Portal web application"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.12"
dependencies = [
  "Flask==3.0.3",
  "waitress==2.1.2",
  "Flask-SocketIO==5.3.6",
  "eventlet==0.40.4",
  "pywebpush==1.14.0",
  "cffi==1.17.1",
  "wheel==0.42.0",
  "cryptography==42.0.8",
]

[tool.setuptools]
py-modules = ["app", "wsgi", "seed_dummy_db"]
